---
title: "Run MKL benchmarks"
author: "Andrie de Vries"
date: "20 July 2015"
output: html_document
---

# Running the tests

The package allows you to run benchmark tests on several different installations of R on the same machine

```{r init, echo=FALSE}
library("version.compare")
library("knitr")
r <- findRscript(version = "3.2.2.*x64")
test.results <- RevoMultiBenchmark(rVersions = r, threads = c(1, 4), scale.factor = 0.1)
```


# Compare results

## Elapsed time (seconds)

```{r compare-results, echo=FALSE}
kable(test.results)
```

## Performance speed-up

```{r performance-speed-up, echo=FALSE}
kable(urbanekPerformance(test.results), digits = 2)
```

## Plot

Compare total elapsed time

```{r plot-results, echo = FALSE}
# time <- sapply(test.results$time, function(x)x[3])
# names(time) <- rNames
# 
# library(ggplot2)
# qplot(x = rNames, y = time, geom = "bar", stat = "identity", fill = I("orange")) + 
#   geom_text(label = round(time, 2)) +
#   theme_bw(16) +
#   xlab(NULL) +
#   ylab("Total time (seconds)") + 
#   ggtitle("Total system test elapsed time") +
#   coord_flip()

plot(test.results)

```
